/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jefeDeObra;

import POJOS.AdministrativoObra;
import POJOS.JefeDeObra;
import POJOS.Material;
import POJOS.MaterialParaObra;
import POJOS.Obra;
import POJOS.Persona;
import dba.MaterialDba;
import dba.ObraDba;
import dba.PersonaDba;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RuChO
 */
public class PanelSolicitarMaterialObra extends javax.swing.JPanel {
    
    //Creamos ArrayList de los objetos que contiene la Tabla para poder trabajar con ellos
    
    
    ArrayList<Obra> obras = new ArrayList<>();
    ArrayList<Material> materiales = new ArrayList<>();
    ArrayList<AdministrativoObra> administrativosDeObra = new ArrayList<>();
    ArrayList<JefeDeObra> jefesDeObra = new ArrayList<>();
    /**
     * Creates new form PanelSolicitarMaterialObra
     */
    public PanelSolicitarMaterialObra() {
        initComponents();
        
        llenar();
        llenarCbo();//Metodo para llenar los ComboBox con los objetos existentes
        deshabilitarBotonesParaTabla();
        limpiar();
        deshabilitar();
    }
DefaultTableModel modelo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        campoCoste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboMaterial = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoFechaSolicitud = new org.jdesktop.swingx.JXDatePicker();
        campoFechaRecepcion = new org.jdesktop.swingx.JXDatePicker();
        cboObras = new javax.swing.JComboBox();
        cboJefeObra = new javax.swing.JComboBox();
        cboAdministrativoObra = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitarMaterialObra = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Jefe de Obra que Solicita Material:");

        jLabel2.setText("Administrativo de Obra que Recoge Material:");

        jLabel6.setText("Obra:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("SOLICITUD MATERIAL PARA OBRA");

        campoCoste.setToolTipText("");
        campoCoste.setFocusable(false);
        campoCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCosteActionPerformed(evt);
            }
        });

        jLabel4.setText("Coste");

        campoCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCantidadKeyReleased(evt);
            }
        });

        jLabel3.setText("Cantidad Material");

        cboMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaterialItemStateChanged(evt);
            }
        });

        jLabel7.setText("Material:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addGap(152, 152, 152))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel9.setText("Fecha Solicitud:");

        jLabel5.setText("Fecha Recepcion:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(campoFechaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboObras.setToolTipText("");
        cboObras.setName(""); // NOI18N
        cboObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboObrasActionPerformed(evt);
            }
        });

        cboJefeObra.setToolTipText("Seleccionar");
        cboJefeObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJefeObraActionPerformed(evt);
            }
        });

        cboAdministrativoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAdministrativoObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboObras, 0, 98, Short.MAX_VALUE)
                            .addComponent(cboJefeObra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboAdministrativoObra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboJefeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboAdministrativoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        tblSolicitarMaterialObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSolicitarMaterialObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitarMaterialObraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitarMaterialObra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNuevo)
                .addComponent(btnGuardar)
                .addComponent(btnBorrar)
                .addComponent(btnModificar)
                .addComponent(btnLimpiar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(verificarCamposRellenosCorrectamente()==true){//Si esta todos los campos rellenos...
            nuevo();
            deshabilitar();
            llenar();
            limpiar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrar();
        limpiar();
        deshabilitar();
        llenar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
        limpiar();
        deshabilitar();
        llenar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        habilitar();
        deshabilitarBotonesParaTabla();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblSolicitarMaterialObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitarMaterialObraMouseClicked
        if (evt.getButton() == 1) {
            int fila = tblSolicitarMaterialObra.getSelectedRow();
            MaterialParaObra materialParaObra=new MaterialParaObra();
            
            try {                 
                materialParaObra=dba.SolicitarMaterialDba.getMaterialParaObra(Integer.parseInt(String.valueOf(tblSolicitarMaterialObra.getValueAt(fila, 0))));

            } catch (SQLException ex) {
                Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                cboObras.setSelectedItem(ObraDba.getObra(materialParaObra.obra.getPK_ID()).getDireccion());
                
                cboJefeObra.setSelectedItem(PersonaDba.getJefeDeObra(materialParaObra.jefeDeObra.getPK_ID()).getNombre());////          
                
                cboAdministrativoObra.setSelectedItem(PersonaDba.getAdministrativoObra(materialParaObra.administrativoObra.getPK_ID()).getNombre());
                
                campoFechaSolicitud.setDate(materialParaObra.getFechaSolicitud());
                campoFechaRecepcion.setDate(materialParaObra.getFechaRecepcion());
                
                campoCantidad.setText(String.valueOf(materialParaObra.getCantidadMaterial()));
                campoCoste.setText(String.valueOf(materialParaObra.getCoste()));
                
                cboMaterial.setSelectedItem(MaterialDba.getMaterial(materialParaObra.material.getPK_ID()).getDescripcion());
                
                habilitar();
                habilitarBotonesParaTabla();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido leer la información en la BD");
            }
        }
    }//GEN-LAST:event_tblSolicitarMaterialObraMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        deshabilitarBotonesParaTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cboJefeObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJefeObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboJefeObraActionPerformed

    private void cboAdministrativoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAdministrativoObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAdministrativoObraActionPerformed

    private void cboObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboObrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboObrasActionPerformed

    private void campoCosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCosteActionPerformed
     
    }//GEN-LAST:event_campoCosteActionPerformed

    private void cboMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaterialItemStateChanged
        if(cboMaterial.isEnabled()==true 
                && !campoCantidad.getText().equals("")
                && cboMaterial.getSelectedIndex()>=0 ){
            actualizarCampoCoste();
        }          
    }//GEN-LAST:event_cboMaterialItemStateChanged

    private void habilitarBotonesParaTabla(){
        ///HABILITAR BOTONES MODIFICACION TABLA
        btnBorrar.setVisible(true);
        btnModificar.setVisible(true);
        btnGuardar.setVisible(false);
    }
    
    private void deshabilitarBotonesParaTabla(){
        ///HABILITAR BOTONES MODIFICACION TABLA
        btnBorrar.setVisible(false);
        btnModificar.setVisible(false);
        btnGuardar.setVisible(true);
    }    
    
    private void campoCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCantidadKeyReleased
        try{
            Float.parseFloat(campoCantidad.getText());
            
            if(campoCantidad.isEnabled()==true 
                    && cboMaterial.getSelectedIndex()>=0 
                    && !campoCantidad.getText().equals("")
                    && Float.parseFloat(campoCantidad.getText())>0){
                       System.out.println("Valor de cboMaterial-->"+cboMaterial.getSelectedIndex());
                       System.out.println("Ejecuto");
                actualizarCampoCoste();
            }

            if(campoCantidad.getText().equals("")){
                actualizarCampoCosteSinCantidad();       
            }
        
        }
        catch(Exception ex){
            System.out.println("No es un texto");
            actualizarCampoCosteSinCantidad(); 
        }


    }//GEN-LAST:event_campoCantidadKeyReleased
    
    
    private void actualizarCampoCoste(){
        Material material=materiales.get(cboMaterial.getSelectedIndex());

        float precioUnitarioMaterial=material.getPrecio();
        float unidadesMaterial=Float.parseFloat(campoCantidad.getText());
        
        float resultadoCoste=precioUnitarioMaterial*unidadesMaterial;
       
        campoCoste.setText(String.valueOf(resultadoCoste));
    }
    
    
    private void actualizarCampoCosteSinCantidad(){
        Material material=materiales.get(cboMaterial.getSelectedIndex());

        float precioUnitarioMaterial=material.getPrecio();
        //float unidadesMaterial=Float.parseFloat(campoCantidad.getText());
        
        float resultadoCoste=precioUnitarioMaterial*0;
       
        campoCoste.setText(String.valueOf(resultadoCoste));
    }
        
    private boolean verificarCamposRellenosCorrectamente(){
            
        boolean correcto=true;
        String errores="Se han encontrado los siguiente errores en su formulario:";

        if(cboObras.getSelectedItem()==null){//Si el campo Obra esta en nulo...
            errores=errores+"\n     *Debe elegir una Obra";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }   
        
        if(cboJefeObra.getSelectedItem()==null){//Si el campo Jefe de Obra esta en nulo...
            errores=errores+"\n     *Debe elegir un Jefe de Obra";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }
        
        if(cboAdministrativoObra.getSelectedItem()==null){//Si el campo Administrativo de Obra esta en nulo...
            errores=errores+"\n     *Debe elegir un Administrativo de Obra";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }        
        
        
        //Tendria que no dejar escribir manualmente en el campo.
        if(campoFechaSolicitud.getDate()==null){//Si el campo Fecha de Solicitud esta en nulo...
            errores=errores+"\n     *Debe elegir una Fecha de Solicitud";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }   
        
        
        //Se podra dejar a Nulo la fecha de recepcion ya que se puede solicitar un material y al tiempo te llegara.... 
        if(campoFechaRecepcion.getDate()==null){//Si el campo Jefe de Obra esta en nulo...
            errores=errores+"\n     *Debe elegir una Fecha de Recepcion";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }  
        

        if(cboMaterial.getSelectedItem()==null){//Si el campo Material esta en nulo...
            errores=errores+"\n     *Debe elegir un Material a la solicitud";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }   
        
        
        //Verificar tambien si es nu numero valido
        if(campoCantidad.getText().equals("")){//Si el campo Cantidad esta en nulo...
            errores=errores+"\n     *Debe elegir una Cantidad d Material a la solicitud";//Añadimos el Error al String que acumula los errores para mostrarlos por el JOptionPane al final
            correcto=false;//Ponemos a false la variable correcto
        }  
        
        
        if(correcto==false){//Si hubo errores...
        /*Sacar un panel con los errores*/
            JOptionPane.showMessageDialog(null,errores);
        }
        
        
        return correcto;
    }
    
    
    private void limpiar(){
        
        cboObras.setSelectedItem(null);//PRUEBAS
        cboJefeObra.setSelectedItem(null);
        cboAdministrativoObra.setSelectedItem(null);
        
        final Calendar instance = Calendar.getInstance();  
        campoFechaSolicitud.setDate(instance.getTime());
        campoFechaRecepcion.setDate(instance.getTime());
        //campoFechaRecepcion.setDate(null);

        cboMaterial.setSelectedItem(null);
        
        campoCantidad.setText("");
        campoCoste.setText("");
    }

    
    /*********************/

    public void habilitar() {   
        cboObras.setEnabled(true);
        cboJefeObra.setEnabled(true);
        cboAdministrativoObra.setEnabled(true);

        campoFechaRecepcion.setEnabled(true);
        campoFechaSolicitud.setEnabled(true);
        
        campoCantidad.setEnabled(true);
        campoCoste.setEnabled(true);
        cboMaterial.setEnabled(true);
        
        btnGuardar.setVisible(true);
        btnLimpiar.setVisible(true);
    }

    public void deshabilitar() {
        cboObras.setEnabled(false);
        cboJefeObra.setEnabled(false);
        cboAdministrativoObra.setEnabled(false);

        campoFechaRecepcion.setEnabled(false);
        campoFechaSolicitud.setEnabled(false);
        
        campoCantidad.setEnabled(false);
        campoCoste.setEnabled(false);
        cboMaterial.setEnabled(false);
        
        btnGuardar.setVisible(false);
        btnLimpiar.setVisible(false);
    }

    public void llenarCbo() {

        try {
            //obras-->ArrayList de todas las obras que se declara al principio
            //dbaObraDba --> Contiene los metodos para tratar la tabla de la BBDD Obra
            obras = dba.ObraDba.getObras();       
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Obras
        //Bucle De Cada Obra del ArrayList Obras, añade un item, en el ComboBox con la Direccion de la Obra
        for (Obra obra : obras) {
            cboObras.addItem(obra.getDireccion());
        }
        
        //Jefes De Obra
        try{
            jefesDeObra=dba.PersonaDba.getJefesDeObra();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (JefeDeObra jefeDeObra:jefesDeObra){
        
            cboJefeObra.addItem(jefeDeObra.getNombre());
        }
        
        //Administrativos De Obra
        try{
            administrativosDeObra=dba.PersonaDba.getAdministrativosObra();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (AdministrativoObra administrativoObra:administrativosDeObra){
        
            cboAdministrativoObra.addItem(administrativoObra.getNombre());
        }
        
        
        //Materiales
        try{
            materiales=dba.MaterialDba.getMateriales();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Material material:materiales){
        
            cboMaterial.addItem(material.getDescripcion());
        }
        
    }
    
    public void llenar() {
        String titulos[] = {"ID Pedido", "Jefe De Obra", "Administrativo Obra", "Cantidad Material", "Coste",
            "Fecha Solicitud", "Fecha Recepcion", "Obra", "Material"};
        modelo = new DefaultTableModel(null, titulos);

        String fila[] = new String[9];
        ArrayList<MaterialParaObra> materialesParaObras = new ArrayList<>();
        try {
            materialesParaObras = dba.SolicitarMaterialDba.getMaterialesParaObras();      
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (MaterialParaObra materialParaObra : materialesParaObras) {
            fila[0] = String.valueOf(materialParaObra.getPK_ID());
            fila[1] = String.valueOf(materialParaObra.jefeDeObra.getNombre());
            fila[2] = String.valueOf(materialParaObra.administrativoObra.getNombre());           
            fila[3] = String.valueOf(materialParaObra.getCantidadMaterial());       
            fila[4] = String.valueOf(materialParaObra.getCoste());                        
            fila[5] = String.valueOf(materialParaObra.getFechaSolicitud());      
            fila[6] = String.valueOf(materialParaObra.getFechaRecepcion()); 
            fila[7] = String.valueOf(materialParaObra.obra.getDireccion());     
            fila[8] = String.valueOf(materialParaObra.material.getDescripcion());         
            
            //PRUEBA

             
             
            modelo.addRow(fila);
        }

        tblSolicitarMaterialObra.setModel(modelo);
        
        deshabilitarBotonesParaTabla();
        deshabilitar();
    }

    public void nuevo() {
        MaterialParaObra materialParaObra=new MaterialParaObra();
        
        try {          
            Obra obra = obras.get(cboObras.getSelectedIndex());
            materialParaObra.setObra(obra);

            JefeDeObra jefeDeObra=jefesDeObra.get(cboJefeObra.getSelectedIndex());
            materialParaObra.setJefeDeObra(jefeDeObra);           

            AdministrativoObra administrativoObra=administrativosDeObra.get(cboAdministrativoObra.getSelectedIndex());
            materialParaObra.setAdministrativoObra(administrativoObra);
            
            materialParaObra.setFechaSolicitud(campoFechaSolicitud.getDate());
            
            materialParaObra.setFechaRecepcion(campoFechaRecepcion.getDate());    
            
            materialParaObra.setCantidadMaterial(Float.parseFloat(campoCantidad.getText()));
            
            materialParaObra.setCoste(Float.parseFloat(campoCoste.getText()));//PROBAR EL PRECIO QUE NOS DA EL MATERIAL¿?
                
            Material material=materiales.get(cboMaterial.getSelectedIndex());
            materialParaObra.setMaterial(material);

            if (dba.SolicitarMaterialDba.insertMaterialParaObra(materialParaObra)) {                
                JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente.");
            }

            deshabilitarBotonesParaTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un Error. Error:" + ex.getMessage());
        }

    }

    public void modificar() {
        int fila = tblSolicitarMaterialObra.getSelectedRow();
        String identificador = (String) tblSolicitarMaterialObra.getValueAt(fila, 0);

        //Obra obra = new Obra();
        MaterialParaObra materialParaObra=new MaterialParaObra();

        try {    
            materialParaObra.setPK_ID(Integer.parseInt(identificador));

            Obra obra = obras.get(cboObras.getSelectedIndex());
            materialParaObra.setObra(obra);
            System.out.println("Paso de obrasetPK");

            JefeDeObra jefeDeObra=jefesDeObra.get(cboJefeObra.getSelectedIndex());
            materialParaObra.setJefeDeObra(jefeDeObra);       
            System.out.println("Paso de JefeObraPK");

            AdministrativoObra administrativo= administrativosDeObra.get(cboAdministrativoObra.getSelectedIndex());
            materialParaObra.setAdministrativoObra(administrativo);

            materialParaObra.setFechaSolicitud(campoFechaSolicitud.getDate());
            
            materialParaObra.setFechaRecepcion(campoFechaRecepcion.getDate());    
            
            materialParaObra.setCantidadMaterial(Float.parseFloat(campoCantidad.getText()));
            
            materialParaObra.setCoste(Float.parseFloat(campoCoste.getText()));//POSIBLE HACERLO CON EL COSTE DEL MATERIAL?¿
            
            Material material=materiales.get(cboMaterial.getSelectedIndex());
            materialParaObra.setMaterial(material);                      

            
        if (dba.SolicitarMaterialDba.updateMaterialParaObra(materialParaObra)) {                
                JOptionPane.showMessageDialog(null, "Datos Modificados");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

    }

    public void borrar() {
        int fila = tblSolicitarMaterialObra.getSelectedRow();
        String identificador = (String) tblSolicitarMaterialObra.getValueAt(fila, 0);

        try {

            if (dba.SolicitarMaterialDba.deleteMaterialParaObra(Integer.valueOf(identificador))) {
                JOptionPane.showMessageDialog(null, "Datos Borrados");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

    }
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JTextField campoCoste;
    private org.jdesktop.swingx.JXDatePicker campoFechaRecepcion;
    private org.jdesktop.swingx.JXDatePicker campoFechaSolicitud;
    private javax.swing.JComboBox cboAdministrativoObra;
    private javax.swing.JComboBox cboJefeObra;
    private javax.swing.JComboBox cboMaterial;
    private javax.swing.JComboBox cboObras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolicitarMaterialObra;
    // End of variables declaration//GEN-END:variables
}
