/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import POJOS.Categoria;
import POJOS.Empleado;
import obra.*;
import POJOS.Obra;
import POJOS.Persona;
import dba.CategoriaDba;
import dba.PersonaDba;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tiburcio
 */
public class DialogoEmpleado extends javax.swing.JDialog {
    /**
     * Creates new form DialogoObra
     */
    public DialogoEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Constructora - Dar de alta a Empleado");
        initComponents();
        panelOperacionesRelativasAUnEmpleado.setVisible(true);
        panelEmpleados.setVisible(false);
        panelDatosDelEmpleado.setVisible(false);
        llenarCategorias();
        this.pack();      
        this.setLocationRelativeTo(null);
    }

    DefaultTableModel modelo;

    public void llenarCategorias() {
        
        try {
            categorias = dba.CategoriaDba.getCategorias();
        } catch (SQLException ex) {
            Logger.getLogger(FrmObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Categoria categoria : categorias) {
            cboCategorias.addItem(categoria.getNombre());
        }
    } 
    
    public void limpiar() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtDni.setText("");
        
        txtUsuario.setText("");
        txtContrasena.setText("");
    }
    
    public void llenar() {
        String titulos[] = {"ID", "Dni", "Nombre", "Apellidos"};
        modelo = new DefaultTableModel(null, titulos);

        String fila[] = new String[4];
        ArrayList<Empleado> empleados = new ArrayList<>();
        try {
            empleados = dba.PersonaDba.getEmpleados();
        } catch (SQLException ex) {
            Logger.getLogger(FrmObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Empleado empleado : empleados) {
            fila[0] = String.valueOf(empleado.getPK_ID());
            fila[1] = empleado.getDni().toString();
            fila[2] = empleado.getNombre().toString();
            fila[3] = empleado.getApellidos().toString();
            
            modelo.addRow(fila);
        }
        tblEmpleados.setModel(modelo);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosDelEmpleado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelarDatos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        avisoAsterisco = new javax.swing.JLabel();
        cboCategorias = new javax.swing.JComboBox<>();
        panelOperacionesRelativasAUnEmpleado = new javax.swing.JPanel();
        btnAlta = new javax.swing.JButton();
        btnModificacion = new javax.swing.JButton();
        btnBorrado = new javax.swing.JButton();
        btnCancelarOperaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelEmpleados = new javax.swing.JPanel();
        btnListaDeEmpleadosOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDatosDelEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        jLabel1.setText("Nombre: *");

        jLabel2.setText("Apellidos: *");

        jLabel3.setText("Telefono: *");

        jLabel4.setText("Dni: *");

        jLabel5.setText("Categoria: *");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelarDatos.setText("Cancelar");
        btnCancelarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDatosActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuario:");

        jLabel7.setText("Contraseña:");

        avisoAsterisco.setText("Los campos marcados con asterisco no pueden dejarse en blanco");

        javax.swing.GroupLayout panelDatosDelEmpleadoLayout = new javax.swing.GroupLayout(panelDatosDelEmpleado);
        panelDatosDelEmpleado.setLayout(panelDatosDelEmpleadoLayout);
        panelDatosDelEmpleadoLayout.setHorizontalGroup(
            panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtApellidos)
                            .addComponent(txtTelefono)
                            .addComponent(txtDni)))
                    .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                        .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btnConfirmar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelarDatos)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosDelEmpleadoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(avisoAsterisco)
                .addGap(32, 32, 32))
        );
        panelDatosDelEmpleadoLayout.setVerticalGroup(
            panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(avisoAsterisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(panelDatosDelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelarDatos))
                .addGap(34, 34, 34))
        );

        panelOperacionesRelativasAUnEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones relativas a un empleado"));

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnModificacion.setText("Modificacion");
        btnModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionActionPerformed(evt);
            }
        });

        btnBorrado.setText("Baja");
        btnBorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorradoActionPerformed(evt);
            }
        });

        btnCancelarOperaciones.setText("Cancelar");
        btnCancelarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOperacionesActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir del programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesRelativasAUnEmpleadoLayout = new javax.swing.GroupLayout(panelOperacionesRelativasAUnEmpleado);
        panelOperacionesRelativasAUnEmpleado.setLayout(panelOperacionesRelativasAUnEmpleadoLayout);
        panelOperacionesRelativasAUnEmpleadoLayout.setHorizontalGroup(
            panelOperacionesRelativasAUnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createSequentialGroup()
                .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrado))
                    .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCancelarOperaciones)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperacionesRelativasAUnEmpleadoLayout.setVerticalGroup(
            panelOperacionesRelativasAUnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnModificacion)
                    .addComponent(btnBorrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelOperacionesRelativasAUnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarOperaciones)
                    .addComponent(btnSalir))
                .addGap(24, 24, 24))
        );

        panelEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el empleado"));

        btnListaDeEmpleadosOK.setText("OK");
        btnListaDeEmpleadosOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDeEmpleadosOKActionPerformed(evt);
            }
        });

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListaDeEmpleadosOK)
                .addGap(212, 212, 212))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListaDeEmpleadosOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosDelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOperacionesRelativasAUnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatosDelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOperacionesRelativasAUnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (quedanVacios()) {   // Metodo siguiente
            JOptionPane.showMessageDialog(null, "Los campos con asterisco no pueden estar vacíos");
        } else {
            Empleado empleado = new Empleado();
            Categoria categoriaSeleccionada = new Categoria();
                
            
            
            for (Categoria categoria : categorias) {
                if (cboCategorias.getSelectedItem() == categoria.getNombre()) {
                    categoriaSeleccionada = categoria;
                }
            }
            try {
                if ("modificacion".equals(operacion)) {
                    int fila = Integer.parseInt (filaDeTabla);
                    String identificador = (String) tblEmpleados.getValueAt(fila, 0);
                    empleado.setPK_ID(Integer.parseInt(identificador));
                }
                
                empleado.setNombre(txtNombre.getText());
                empleado.setApellidos(txtApellidos.getText());
                empleado.setTelefono(txtTelefono.getText());
                empleado.setDni(txtDni.getText());
                empleado.setCategoria(categoriaSeleccionada);
                if ("".equals(txtUsuario.getText())) { empleado.setUsuario("--");
                } else {empleado.setUsuario(txtUsuario.getText());}
                if ("".equals(txtContrasena.getText())) { empleado.setContra("--");
                } else {empleado.setContra(txtContrasena.getText());}
                
            
                if ("alta".equals(operacion)) { 
                    if (dba.PersonaDba.insertEmpleado(empleado)) {
                        JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
                    }
                } else if ("modificacion".equals(operacion)) {
                    if (dba.PersonaDba.updateEmpleado(empleado)) {
                        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
                    }
                }
                limpiar();
                panelDatosDelEmpleado.setVisible(false);
                panelOperacionesRelativasAUnEmpleado.setVisible(true);
                        
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Se ha producido un Error. Error:" + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    
    private boolean quedanVacios() {
        boolean quedanVacios = true;
        if (!"".equals(txtNombre.getText()) && !"".equals(txtApellidos.getText()) && !"".equals(txtTelefono.getText()) && !"".equals(txtDni.getText())   ) {
            quedanVacios = false;
        }
        return quedanVacios;
    }

    
    private void btnCancelarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDatosActionPerformed
        limpiar();
        panelDatosDelEmpleado.setVisible(false);
        panelOperacionesRelativasAUnEmpleado.setVisible(true);
        this.pack();      
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarDatosActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        panelOperacionesRelativasAUnEmpleado.setVisible(false);
        panelDatosDelEmpleado.setVisible(true);
        this.pack();      
        this.setLocationRelativeTo(null);
        operacion = "alta";
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnCancelarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOperacionesActionPerformed
        limpiar();
        dispose();
    }//GEN-LAST:event_btnCancelarOperacionesActionPerformed

    private void btnModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionActionPerformed
        panelOperacionesRelativasAUnEmpleado.setVisible(false);
        panelEmpleados.setVisible(true);
        this.pack();      
        this.setLocationRelativeTo(null);
        llenar();
        operacion = "modificacion";
    }//GEN-LAST:event_btnModificacionActionPerformed

    private void btnBorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorradoActionPerformed
        panelOperacionesRelativasAUnEmpleado.setVisible(false);
        panelEmpleados.setVisible(true);
        this.pack();      
        this.setLocationRelativeTo(null);
        llenar();
        operacion = "baja";
    }//GEN-LAST:event_btnBorradoActionPerformed

    private void btnListaDeEmpleadosOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDeEmpleadosOKActionPerformed
        llenar();
        if (operacion == "modificacion"){
            
            panelEmpleados.setVisible(false);
            panelDatosDelEmpleado.setVisible(true);
            this.pack();      
            this.setLocationRelativeTo(null);
            
        } else if (operacion == "baja") {
        
            int fila = Integer.parseInt(filaDeTabla);
            String identificador = (String) tblEmpleados.getValueAt(fila, 0);

            try {
                if (dba.PersonaDba.deletePersona(Integer.valueOf(identificador))) {
                    JOptionPane.showMessageDialog(null, "Datos Borrados. El empleado ha sido eliminado del registro,\n"
                                                        + "despedido de la empresa y condenado a la agonia de depender\n"
                                                        + "de la caridad para sobrevivir. Las previsibles dificultades\n"
                                                        + "economicas que atravesara su familia se veran\n"
                                                        + "agravadas por los problemas de alcoholismo\n"
                                                        + "consecuencia de la depresion que esta persona sufrira al\n"
                                                        + "sentirse un inutil incapaz de sacar adelante a sus tres\n"
                                                        + "hijos pequenos, que se marcharan con su madre y jamas\n"
                                                        + "volveran a tener contacto con aquel a quien consideraran\n"
                                                        + "para siempre un fracasado. Este morira solo, hundido en el\n"
                                                        + "alcohol y la tristeza, de un infarto sentado en el desvencijado\n"
                                                        + "sillon de su cochambrosa vivienda social mientras en la\n"
                                                        + "television pasan un episodio repetido de Cuentame.");
                
                }
            panelEmpleados.setVisible(false);
            panelOperacionesRelativasAUnEmpleado.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnListaDeEmpleadosOKActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        if (evt.getButton() == 1) {
            int fila = tblEmpleados.getSelectedRow();
            filaDeTabla = String.valueOf(fila);
            Empleado empleado = new Empleado();
            try {
                empleado = dba.PersonaDba.getEmpleado(Integer.parseInt(String.valueOf(tblEmpleados.getValueAt(fila, 0))));
            } catch (SQLException ex) {
                Logger.getLogger(FrmObra.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                txtNombre.setText(empleado.getNombre());
                txtApellidos.setText(empleado.getApellidos());
                txtTelefono.setText(empleado.getTelefono());
                txtDni.setText(empleado.getDni());
                txtUsuario.setText(empleado.getUsuario());
                txtContrasena.setText(empleado.getContra());

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido leer la información en la BD");
            }
        }
        
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoEmpleado dialog = new DialogoEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoAsterisco;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBorrado;
    private javax.swing.JButton btnCancelarDatos;
    private javax.swing.JButton btnCancelarOperaciones;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnListaDeEmpleadosOK;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatosDelEmpleado;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelOperacionesRelativasAUnEmpleado;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    String filaDeTabla;
    ArrayList<Categoria> categorias = new ArrayList<>();
    String operacion;
}
