/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mostrarBalanceDeObra;

import POJOS.Empleado;
import POJOS.Obra;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author samue
 */
public class DialogoMostrarBalanceDeObra extends javax.swing.JDialog {
Empleado empleado;
ArrayList<Obra> obras = new ArrayList<>();
Obra obraSeleccionada = new Obra();
String textoA;
String textoB;
String textoC;
String textoD;

float costeA;
float costeB;
float costeC;
float costeD;

    /**
     * Creates new form MostrarBalanceDeObra
     */
    public DialogoMostrarBalanceDeObra(java.awt.Frame parent, boolean modal, Empleado empleado) {
        super(parent, modal);
        initComponents();
        ocultar();
        llenarCbo();
        this.empleado=empleado;
        
    }
    
    public void ocultar(){
        lbCosteMateriales.setVisible(false);
        lbEstadoCobro.setVisible(false);
        lbEstadoEjecucion.setVisible(false);
        lbManoObra.setVisible(false);
    }
    
    public void mostrar(){
        lbCosteMateriales.setVisible(true);
        lbEstadoCobro.setVisible(true);
        lbEstadoEjecucion.setVisible(true);
        lbManoObra.setVisible(true);
    }
    
    public void llenarCbo() {
        try {
            obras = dba.ObraDba.getObras();
        } catch (SQLException ex) {
            Logger.getLogger(DialogoMostrarBalanceDeObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Obra obra : obras) {        
            cboObra.addItem(obra.getDireccion());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboObra = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lbCosteMateriales = new javax.swing.JLabel();
        lbManoObra = new javax.swing.JLabel();
        lbEstadoEjecucion = new javax.swing.JLabel();
        lbEstadoCobro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selecciona una obra:");

        cboObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboObraActionPerformed(evt);
            }
        });

        jLabel2.setText("Coste de materiales de la obra ejecutada:");

        jLabel3.setText("Coste de mano de obra ejecutada:");

        jLabel4.setText("Estado de facturación:");

        jLabel5.setText("Estado de cobro:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboObra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCosteMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbManoObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEstadoEjecucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEstadoCobro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbCosteMateriales))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbManoObra))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbEstadoEjecucion))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbEstadoCobro))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboObraActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            obras = dba.ObraDba.getObras();
        } catch (SQLException ex) {
            Logger.getLogger(DialogoMostrarBalanceDeObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        obraSeleccionada = obras.get(cboObra.getSelectedIndex());
        
        //a) Coste de materiales de la obra ejecutada(Previsto  Real  Desviación +-%)
        costeA = obraSeleccionada.getEstimacionCosteMateriales()*((obraSeleccionada.getPorcentajeDeObraEjecutado())/100);
        textoA=String.format("%.2f", costeA);
        lbCosteMateriales.setText(String.valueOf(textoA+" €"));
        
        
        //b) Coste de mano de obra ejecutada(Previsto  Real  Desviación +-%)
        costeB = (obraSeleccionada.getEstimacionCosteManoDeObra())*((obraSeleccionada.getPorcentajeDeObraEjecutado())/100);
        textoB=String.format("%.2f", costeB);
        lbManoObra.setText(String.valueOf(textoB+" €"));
        
        
        //c) Estado de facturación (%Obra ejecutada  %Obrafacturada  +- % Desviación)
        costeC = (obraSeleccionada.getCantidadFacturada())*((obraSeleccionada.getPorcentajeDeObraEjecutado())/100);
        textoC=String.format("%.2f", costeC);
        lbEstadoEjecucion.setText(String.valueOf(textoC+" €"));
        
        
        //d) Estado de cobro (%Obra ejecutada  %Obracobrada  +- % Desviación)
        costeD = ((obraSeleccionada.getCantidadCobrada())*100) / (obraSeleccionada.getCantidadFacturada());
        textoD=String.format("%.2f", costeD);
        lbEstadoCobro.setText(String.valueOf(textoD+" %")); 
        
        mostrar();
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cboObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbCosteMateriales;
    private javax.swing.JLabel lbEstadoCobro;
    private javax.swing.JLabel lbEstadoEjecucion;
    private javax.swing.JLabel lbManoObra;
    // End of variables declaration//GEN-END:variables
}
