/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleadoAlmacen;

import POJOS.AdministrativoObra;
import POJOS.EmpleadoAlmacen;
import POJOS.JefeDeObra;
import POJOS.Material;
import POJOS.MaterialParaObra;
import POJOS.Obra;
import dba.MaterialDba;
import dba.ObraDba;
import dba.PersonaDba;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jefeDeObra.PanelSolicitarMaterialObra;
import login.FrmLogin;
import login.FrmMain;

/**
 *
 * @author Acer Aspire
 */
public class AsignarMaterialesAObra extends javax.swing.JPanel {

    ArrayList<Obra> obras = new ArrayList<>();
    ArrayList<Material> materiales = new ArrayList<>();
    ArrayList<AdministrativoObra> administrativosDeObra = new ArrayList<>();
    ArrayList<JefeDeObra> jefesDeObra = new ArrayList<>();
    
    
    EmpleadoAlmacen empleadoAlmacenUsuario=new EmpleadoAlmacen();  
    /*ESPECIFICOS DE MATERIALASIGNADOAOBRA*/
    //ArrayList<Obra> obras = new ArrayList<>();
    //ArrayList<Material> materiales = new ArrayList<>();    
    
    
    
    
    public AsignarMaterialesAObra(){
        initComponents();
        
        try{
            identificarEmpleado();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }    
        llenar();
        limpiar();
        deshabilitar();
    }
DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        campoCoste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtObra = new javax.swing.JTextField();
        txtJefeDeObra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaSolicitud = new javax.swing.JTextField();
        ckboxAsignar = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitarMaterialObra = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMiMaterialObraAsignado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ASIGNAR MATERIAL A OBRA");

        campoCoste.setToolTipText("");
        campoCoste.setFocusable(false);
        campoCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCosteActionPerformed(evt);
            }
        });

        jLabel4.setText("Coste");

        jLabel3.setText("Cantidad Material");

        jLabel7.setText("Material:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(campoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(152, 152, 152))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel10.setText("Jefe de Obra que Solicita Material:");

        jLabel6.setText("Obra:");

        jLabel9.setText("Fecha Solicitud:");

        ckboxAsignar.setText("ASIGNAR");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtObra)
                            .addComponent(txtJefeDeObra)
                            .addComponent(txtFechaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckboxAsignar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtJefeDeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(ckboxAsignar))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        tblSolicitarMaterialObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSolicitarMaterialObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitarMaterialObraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitarMaterialObra);

        jLabel1.setText("Material Solicitado Para Obra Sin Asignar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));

        tbMiMaterialObraAsignado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMiMaterialObraAsignado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMiMaterialObraAsignadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMiMaterialObraAsignado);

        jLabel2.setText("Mi Material Asignado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(255, 255, 255))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(ckboxAsignar.isSelected()==true){//Si esta todos los campos rellenos...
            modificarConTick();

        }
        else{
            modificarQuitarTick();
        }
        
        deshabilitar();
        llenar();
        limpiar();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblSolicitarMaterialObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitarMaterialObraMouseClicked
        if (evt.getButton() == 1) {
            int fila = tblSolicitarMaterialObra.getSelectedRow();
            MaterialParaObra materialParaObra=new MaterialParaObra();
  
            try {
                materialParaObra=dba.SolicitarMaterialDba.getMaterialParaObra(Integer.parseInt(String.valueOf(tblSolicitarMaterialObra.getValueAt(fila, 0))));

            } catch (SQLException ex) {
                Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
            }

              
                if(materialParaObra.empleadoAlmacen.getPK_ID()!=0){
                    ckboxAsignar.setSelected(true);
                }else{
                    ckboxAsignar.setSelected(false);
               }
                   
            
            
            try {
                txtObra.setText(ObraDba.getObra(materialParaObra.obra.getPK_ID()).getDireccion());              
                txtJefeDeObra.setText(PersonaDba.getJefeDeObra(materialParaObra.jefeDeObra.getPK_ID()).getNombre());////
                txtFechaSolicitud.setText(String.valueOf(materialParaObra.getFechaSolicitud()));
                campoCantidad.setText(String.valueOf(materialParaObra.getCantidadMaterial()));
                campoCoste.setText(String.valueOf(materialParaObra.getCoste()));
                txtMaterial.setText(MaterialDba.getMaterial(materialParaObra.material.getPK_ID()).getDescripcion());
                
         
                btnGuardar.setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido leer la información en la BD");
            }
        }
    }//GEN-LAST:event_tblSolicitarMaterialObraMouseClicked

    private void campoCosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCosteActionPerformed

    }//GEN-LAST:event_campoCosteActionPerformed

    private void tbMiMaterialObraAsignadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMiMaterialObraAsignadoMouseClicked
  //IDENTICA A LA ANTERIOR...PROBAR CON METODO!!
        if (evt.getButton() == 1) {
            int fila = tbMiMaterialObraAsignado.getSelectedRow();
            MaterialParaObra materialParaObra=new MaterialParaObra();
  
            try {
                materialParaObra=dba.SolicitarMaterialDba.getMaterialParaObra(Integer.parseInt(String.valueOf(tbMiMaterialObraAsignado.getValueAt(fila, 0))));

            } catch (SQLException ex) {
                Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
            }

              
                if(materialParaObra.empleadoAlmacen.getPK_ID()!=0){
                    ckboxAsignar.setSelected(true);
                }else{
                    ckboxAsignar.setSelected(false);
               }
                   
            
            
            try {
                txtObra.setText(ObraDba.getObra(materialParaObra.obra.getPK_ID()).getDireccion());              
                txtJefeDeObra.setText(PersonaDba.getJefeDeObra(materialParaObra.jefeDeObra.getPK_ID()).getNombre());////
                txtFechaSolicitud.setText(String.valueOf(materialParaObra.getFechaSolicitud()));
                campoCantidad.setText(String.valueOf(materialParaObra.getCantidadMaterial()));
                campoCoste.setText(String.valueOf(materialParaObra.getCoste()));
                txtMaterial.setText(MaterialDba.getMaterial(materialParaObra.material.getPK_ID()).getDescripcion());
                
         
                btnGuardar.setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido leer la información en la BD");
            }
        }
        
    }//GEN-LAST:event_tbMiMaterialObraAsignadoMouseClicked

    private void identificarEmpleado() throws SQLException{
        try{
            empleadoAlmacenUsuario=dba.PersonaDba.getEmpleadoAlmacen(FrmLogin.empleadoLogin.getPK_ID());
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
    }
    
    
    private void limpiar(){
        
        txtObra.setText(null);//PRUEBAS
        txtJefeDeObra.setText(null);
        txtFechaSolicitud.setText(null);
        txtMaterial.setText(null);      
        campoCantidad.setText("");
        campoCoste.setText("");
        ckboxAsignar.setSelected(false);
    }

    
    /*********************/


    public void deshabilitar() {
        txtObra.setEnabled(false);
        txtJefeDeObra.setEnabled(false);
   
        txtFechaSolicitud.setEnabled(false);
        
        campoCantidad.setEnabled(false);
        campoCoste.setEnabled(false);
        txtMaterial.setEnabled(false);
        
        btnGuardar.setVisible(false);
    }

    
    public void llenar() {
        String titulos[] = {"ID Pedido", "Jefe De Obra", "Administrativo Obra", "Cantidad Material", "Coste",
            "Fecha Solicitud", "Fecha Recepcion", "Obra", "Material"};
        modelo = new DefaultTableModel(null, titulos);

        String fila[] = new String[9];
        ArrayList<MaterialParaObra> materialesParaObras = new ArrayList<>();
        try {
            materialesParaObras = dba.SolicitarMaterialDba.getMaterialesParaObrasSinAsignar();      
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (MaterialParaObra materialParaObra : materialesParaObras) {
            fila[0] = String.valueOf(materialParaObra.getPK_ID());
            fila[1] = String.valueOf(materialParaObra.jefeDeObra.getNombre());
            fila[2] = String.valueOf(materialParaObra.administrativoObra.getNombre());           
            fila[3] = String.valueOf(materialParaObra.getCantidadMaterial());       
            fila[4] = String.valueOf(materialParaObra.getCoste());                        
            fila[5] = String.valueOf(materialParaObra.getFechaSolicitud());      
            fila[6] = String.valueOf(materialParaObra.getFechaRecepcion()); 
            fila[7] = String.valueOf(materialParaObra.obra.getDireccion());     
            fila[8] = String.valueOf(materialParaObra.material.getDescripcion());         
            
            //PRUEBA

             
             
            modelo.addRow(fila);
        }

        tblSolicitarMaterialObra.setModel(modelo);
        
        deshabilitar();
        
        //prueba
        llenarMisAsignaciones();
    }
    
    
    
        public void llenarMisAsignaciones() {
        String titulos[] = {"ID Pedido", "Jefe De Obra", "Administrativo Obra", "Cantidad Material", "Coste",
            "Fecha Solicitud", "Fecha Recepcion", "Obra", "Material"};
        modelo = new DefaultTableModel(null, titulos);

        String fila[] = new String[9];
        ArrayList<MaterialParaObra> materialesParaObras = new ArrayList<>();
        try {
            materialesParaObras = dba.SolicitarMaterialDba.getMaterialesParaObrasAsignadosPorMi();      
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitarMaterialObra.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (MaterialParaObra materialParaObra : materialesParaObras) {
            fila[0] = String.valueOf(materialParaObra.getPK_ID());
            fila[1] = String.valueOf(materialParaObra.jefeDeObra.getNombre());
            fila[2] = String.valueOf(materialParaObra.administrativoObra.getNombre());           
            fila[3] = String.valueOf(materialParaObra.getCantidadMaterial());       
            fila[4] = String.valueOf(materialParaObra.getCoste());                        
            fila[5] = String.valueOf(materialParaObra.getFechaSolicitud());      
            fila[6] = String.valueOf(materialParaObra.getFechaRecepcion()); 
            fila[7] = String.valueOf(materialParaObra.obra.getDireccion());     
            fila[8] = String.valueOf(materialParaObra.material.getDescripcion());         
            
            //PRUEBA

             
             
            modelo.addRow(fila);
        }

        tbMiMaterialObraAsignado.setModel(modelo);
        
        deshabilitar();
    }


    public void modificarConTick() {
        int fila = tblSolicitarMaterialObra.getSelectedRow();
        String identificador = (String) tblSolicitarMaterialObra.getValueAt(fila, 0);

        //Obra obra = new Obra();
        MaterialParaObra materialParaObra=new MaterialParaObra();

        try {    
            materialParaObra.setPK_ID(Integer.parseInt(identificador));
            materialParaObra.setEmpleadoAlmacen(empleadoAlmacenUsuario);
   
        if (dba.SolicitarMaterialDba.updateAsignacionMaterialParaObra(materialParaObra)) {                
                JOptionPane.showMessageDialog(null, "Datos Modificados");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

    }
    
    public void modificarQuitarTick() {
        int fila = tbMiMaterialObraAsignado.getSelectedRow();
        String identificador = (String) tbMiMaterialObraAsignado.getValueAt(fila, 0);

        //Obra obra = new Obra();
        MaterialParaObra materialParaObra=new MaterialParaObra();

        try {    
            materialParaObra.setPK_ID(Integer.parseInt(identificador));
            
        if (dba.SolicitarMaterialDba.updateAsignacionMaterialParaObraANulo(materialParaObra)) {                
                JOptionPane.showMessageDialog(null, "Datos Modificados");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

    }    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JTextField campoCoste;
    private javax.swing.JCheckBox ckboxAsignar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbMiMaterialObraAsignado;
    private javax.swing.JTable tblSolicitarMaterialObra;
    private javax.swing.JTextField txtFechaSolicitud;
    private javax.swing.JTextField txtJefeDeObra;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtObra;
    // End of variables declaration//GEN-END:variables
}
